### ISSUE TITLE
ExposeCreativeMode

### ISSUE THREAD

**Issue by Badboys9998** [Velociraptor115/DSPMods#1]
It don't work can u fix please.

**Comment by Velociraptor115** [comment]
Can you provide any information on the issue so that I can help fix it?

- Which version of ExposeCreativeMode mod are you using?
- Are you using r2modman to install mods?
- If so, are the following mods also installed (should happen automatically, but can't hurt to double-check)
  - BepInEx 5.4.11
  - DSPModSave 1.1.2
  - CommonAPI 1.2.1
  - LDBTool 1.8.0
![image](https://user-images.githubusercontent.com/21120504/145339960-82f79b70-e66c-48d4-b0bf-d4d0ec9de138.png)

- Is the game version 0.8.23.9989 ?
![image](https://user-images.githubusercontent.com/21120504/145340261-a282d7e4-91e8-4fa5-a9e8-d76181c4a410.png)

- If you are using version 0.0.4 of the mod, are you able to see the keybinds like this
![image](https://user-images.githubusercontent.com/21120504/145340465-29a5845c-98df-4a23-8cff-ce007b100f43.png)

- Note that you have to be in **Creative Mode** for the (Creative Mode) controls to work
If Creative mode is enabled, you will see it as highlighted below
![image](https://user-images.githubusercontent.com/21120504/145340583-e0af9566-193d-4e75-b34f-fed3e6d63544.png)

**Comment by Velociraptor115** [comment]
If all of that works fine, but the individual controls are not working, can you elaborate on what does not work?

**Comment by Badboys9998** [comment]
Everything is working good but how do you turn off the Creative Mode or can you. On my screen the Creative Mode is under my name but no big deal.

**Comment by Badboys9998** [comment]
BepInEx 5.4.11 is at 5.4.17 now

**Comment by Velociraptor115** [comment]
> Everything is working good but how do you turn off the Creative Mode or can you.

You can just press the keybind for "Toggle Creative Mode" again to turn it off
The default keybind should be "Shift + F4"
