### ISSUE TITLE
No longer able to type min/max?

### ISSUE THREAD

**Issue by ChoadScholar** [Velociraptor115/DSPMods#7]
**Mod**
UIEnhancements 0.0.2

**Describe the bug**
No longer able to type to edit station request levels.  Loved this feature!

**To Reproduce**
Open PLS/ILS screen
Click on level to type
No effect
Must drag slider like a savage

**Comment by Velociraptor115** [comment]
@ChoadScholar I think that's probably because I reset all the enhancements to be disabled on first install

Few folks had requested that they don't want the enhancements to be automatically enabled as this is not a specific mod but rather a mixed bag of changes, not all of which everyone would want to have

Are you unable to enable it as per [instructions here]?(https://github.com/Velociraptor115/DSPMods/tree/main/UIEnhancements/Thunderstore#enhancements)
Let me know if you can't enable it

**Comment by ChoadScholar** [comment]
Looks like I had a bad installation of another mod with the same name and a typo, probably causing a conflict.  Deleted both and reinstalled latest version -- all is right and all of my ILS max levels are set to 6969. as they should be.

Thanks!

**Comment by Velociraptor115** [comment]
Ah, right, I had made a typo with my initial upload 😅 
Glad to hear it works
